#!/usr/bin/env python

import fileinput
import subprocess
import datetime

# Path to feed.xml
fpath="/Users/ni41435_ca/Documents/bioc_git_transition/hooks/common/feed.xml"

FEED="""<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:thr="http://purl.org/syndication/thread/1.0" xml:lang="en">
<title type="text">Bioconductor GIT feed</title>
%s
</feed>"""


def rss_feed(oldrev, newrev, refname):
    """Pre-receive hook to check for duplicate SVN commits."""
    try:
        latest_commit = subprocess.check_output([
            "git", "log", oldrev + ".." + newrev,
            "--pretty=format:%h|%an|%s|%at"
            ])
    except Exception as e:
        print("Exception: %s" % e)
        pass
    if latest_commit:
        commit_id, author, message, timestamp = latest_commit.split("|")
    date = datetime.datetime.fromtimestamp(float(timestamp)).strftime('%Y-%m-%d %H:%M:%S')
    entry = "<entry>\n\
      <commit_id>%s</commit_id>\n\
      <author><name>%s</name></author>\n\
      <title>%s</title>\n\
      <published>%s</published>\n\
      <summary type=\"html\">\n\
      <![CDATA[\n\
      ]]>\n\
      </summary>\n\
    </entry>" % (commit_id, author, message, date)
    # Not sure why we add the commits variable after the 3rd line in XML file
    new_feed = FEED % entry
    with open(fpath, "w") as f:
        f.write(new_feed)
    return


#for line in fileinput.input():
#    std_input = line.split(" ")
#    oldrev, newrev, refname = [item.strip() for item in std_input]

rss_feed("67ccbb7b161b5736cb0202a2a783b32e68c689dc", "d83552d75588957a54222c010e8c1311cac29464","refs/head/master")

