#!/bin/sh
#
# This script adds every pushed commit info to XML file
# Make sure to place it in your bare repo's /hooks dir and make it executable
#

git update-server-info

FILE="/Users/ni41435_ca/Documents/bioc_git_transition/hooks/common/feed.xml"

# Get diapasone of pushed commits
while read oldrev newrev refname
do
    # Loop over pushed commits and concatenate XML data into $commits variable
    commits=$(git log $oldrev..$newrev --pretty=format:'%h|%an|%s|%at' |
    while IFS='|' read hash author message timestamp
    do
    
    date=`date -d @$timestamp +%Y-%m-%dT%H:%M:%SZ`
    echo "\<entry\>\n\
      \<author\>\<name\>$author\<\/name\>\<\/author\>\n\
      \<title\>$message\<\/title\>\n\
      \<published\>$date\<\/published\>\n\
      \<summary type=\"html\"\>\n\
      \<![CDATA[\n\
      ]]\>\n\
      \<\/summary\>\n\
    \<\/entry\>"

  done)

  # Add $commits variable value after 3rd line in XML file
  sed -i "3 a $(echo $commits)" $FILE
done
