## Public beta

team

- [ ] SSH keys

    - all team keys added

- [ ] Review current state

    - all packages under `packages/`

      - read / write: `git clone git@git.bioconductor.org:packages/<pkgname>`
      - read-only: `git clone https://git.bioconductor.org/packages/<pkgname>`

    - 'manifest'

      - `git clone git@git.bioconductor.org:admin/manifest`
      - `git clone https://git.bioconductor.org/admin/manifest`
      - `git log --follow` for full history

- [ ] SPB

    - No changes?!

- [ ] BBS

    - Has a full build been run?
      - Need for initial clone of all pkgs -- `git clone --depth 1`
      - How long does a shallow update take? for all pkgs, `git pull`

- Other ??

- [ ] `bioc_git_transition`

    - [ ] GlobalAncova
    - [ ] psygenet2r
    - [ ] minfiDataEPIC ...and other true positives
    - [x] clean up 'doc' directory so only beta-tester docs present
      (create `admin-doc` or similar)
    - [ ] manifest repository should not be large

- [ ] New packages

    - [ ] BiocCheck -- option for new packages only
      - [ ] Cloned repo size
      - [ ] SSH key present


    - [ ] GitContribution repos
      - Accept:
        - [ ] harvest ssh key
        - [ ] add bare repo, only 'master' branch
          - `git clone --bare --single-branch --branch master <repos>`

- [ ] git push hooks?

    - size
    - disable force push?

- [ ] other functionality

    - BBS / coverage; codecov.io; uses Bioconductor-mirror ?
    - svn commit hooks

public

- [ ] harvest ssh keys

    - github user: from github
    - non-github user: ssh public key
    - https://goo.gl/forms/eg36vcBkIUjfZfLe2

- [ ] email to bioc-devel

    - General
      - schedule: transition July 31 (Monday after conference)
      - fate of github.com/Bioconductor-mirror
        - will not be updated after transition

    - Beta
      - Link to https://goo.gl/forms/eg36vcBkIUjfZfLe2
      - Beta test period open
      - Beta commits: purposeful commits that don't break packages;
        commits go away at end of test period
      - Point to [scenarios][]
      - New to github? https://try.github.io

[scenarios]: https://github.com/Bioconductor/bioc_git_transition/tree/master/doc

## Transition

2-stage transition?

- Data experiment first (1-2 weeks)
- Challenge to users of two separate systems -- commit my changes to
  data experiment via git, then commit software changes to svn

What if things go wrong?

- Switch back to SVN?
  - Easy for BBS, but then commits in git but not SVN
  - Herve: don't go backward! Fix instead

1. (T - 1 day)

    - Add last package(s) to svn
    - Disable svn commits to data experiment packages
      - Pre-commit hook indicating what's going on
    - Rebuild all git 'bare' repositories

1. (T - 6 hours)

    - Stop all commits to svn. Ever.
    - Stop all (beta) commits to git
    - `rm -rf repositories/packages/*`
    - `git svn rebase` all packages

1. (T - 0 hours)

    - Enable commits to git
    - Switch BBS

1. (T + n hours)

    - Hilarity
