#!/usr/bin/env bash

#
# Pre-receive hook that will block any new commits that contain files larger than 5Mb in size.
#

GITCMD="/usr/bin/git"
zero_commit="0000000000000000000000000000000000000000"
MAXSIZE="5000000" # 5MB limit on file size

# Read stdin for ref information
while read oldrev newrev refname; do
    # Skip branch deletions
    if [ "${newrev}" = "${zero_commit}" ]; then
        continue;
    fi

    # Set oldrev properly if this is branch creation.
    if [ "${oldrev}" = "${zero_commit}" ]; then
        oldrev="HEAD"
    fi

    # Get list of files to look at using git diff
    for file in $($GITCMD diff --stat --name-only --diff-filter=ACMRT ${oldrev}..${newrev}); do
        # Get the size of this file
        size=$($GITCMD cat-file -s ${newrev}:${file})
	    # Check to see if for some reason we didn't get a size
        if [ ! -z ${size} ]; then
            # Compare filesize to MAXSIZE
            if [ "${size}" -gt "${MAXSIZE}" ]; then
                # Send output back to the user about oversized files.
                echo "Error: ${file} larger than 5Mb. Please see Biocondcutor guidelines"
                echo "    https://bioconductor.org/developers/package-guidelines/"
                # Fail here
                exit 1
            fi # End size comparison
        fi   # End check for empty size
    done   # End list of files
done     # End reading stdin

# If successful, pass
exit 0
