#!/usr/bin/env python

import subprocess
import sys
import fileinput

#
# Pre-receive hook that will block any new commits
# that contain files larger than 5Mb in size and duplicate commits
#


ZERO_COMMIT = "0000000000000000000000000000000000000000"
MAXSIZE = "5000000"  # 5MB limit on file size
ERROR_DUPLICATE_COMMITS = """ERROR

    There are duplicate commits in your commit history, These cannot
    be pushed to the Bioconductor git server. Please make sure that
    this is resolved.

    Take a look at the documentation to fix this,
    https://bioconductor.org/developers/how-to/git/sync-existing-repositories/,
    particularly, point #8 (force Bioconductor master to Github
    master).

    For more information, or help resolving this issue, contact
    <bioc-devel@r-project.org>. Provide the error, the package name
    and any other details we might need.

Duplicate commits:

    %s
    %s

Use

    git show %s
    git show %s

to see body of commits.
"""

ERROR_LARGE_FILE = """ERROR
%s larger than 5Mb. Please see Biocondcutor package guidelines
https://bioconductor.org/developers/package-guidelines/.
"""


def disable_large_files(oldrev, newrev, refname):
    """Pre-receive hook to check for large files."""
    # Check for zero commit, check branch deletions
    if newrev == ZERO_COMMIT:
        pass

    # set oldrec properly if this is branch creation
    if oldrev == ZERO_COMMIT:
        oldrev = "HEAD"

    list_files = subprocess.check_out(["git", "diff",
                                       "--name-only", "--diff-filter=ACMRT",
                                       oldrev + ".." + newrev])
    for fl in list_files:
        size = subprocess.check_out(["git", "cat-file", "-s",
                                     newrev + ":" + fl])
        #  Check to see if for some reason we didn't get a size
        if not size:
            # Compare filesize to MAXSIZE
            if size >= MAXSIZE:
                print(ERROR_LARGE_FILE % fl)
                sys.exit(1)
    sys.exit(0)
    return


def check_commit_pairs(oldrev, newrev, refname):
    """Pre-receive hook to check for duplicate commits."""
    if newrev == ZERO_COMMIT:
        continue
    try:
        commit_list = subprocess.check_output(["git",
                                               "rev-list",
                                               newrev, "-n", "10"])
    except Exception as e:
        print("Exception: %s" % e)
        pass
    commit_list = commit_list.split("\n")
    commit_list = [item for item in commit_list if len(item)>0]
    # For each of the first 10 pairs, check diff

    for i in xrange(len(commit_list) - 1):
        first = commit_list[i]
        second = commit_list[i+1]

        # use 'show' to test for empty commits,
        # else git diff will report no diffs
        body1 = subprocess.check_output(["git", "show",
                                         "--format=%b", first]).strip()
        if not body1:
            continue

        body2 = subprocess.check_output(["git", "show",
                                         "--format=%b", second]).strip()
        if not body2:
            continue

        # Get diff of two commits
        diff = subprocess.check_output(["git", "diff", first, second])
        # If the diff of two commits is empty, means they are the same.
        # i.e duplicate
        if not diff:
            print(ERROR_DUPLICATE_COMMITS % (first, second, first, second))
            sys.exit(1)
    return


# This code doesn't run; enable for local testing.
# to use:
#
#   1. Toggle 'False' to 'True'
#   2. make a git repostiory
#   3. create invalid commit history
#   4. run python prevent-duplicate-commits from repository root
#   5. create branch and repeat for each test
if False:
    newrev = subprocess.check_output([
        "git", "log", "-1", "--format=%H"
    ]).strip()

    commit_list = subprocess.check_output([
        "git", "rev-list", "HEAD", "-n", "10"
    ])
    check_commit_pairs(commit_list)
    sys.exit(0)

if __name__ == "__main__":
    for line in fileinput.input():
        std_input = line.split(" ")
        oldrev, newrev, refname = std_input[0], std_input[1], std_input[2]

        disable_large_files(oldrev, newrev, refname)
        check_commit_pairs(oldrev, newrev, refname)
