def avoid():
    avoid = ['bioc_1.6.manifest',
             'bioc_1.7.manifest',
             'bioc_1.8.manifest',
             'bioc_1.9.manifest',
             'bioc_2.0.manifest',
             'bioc_2.1.manifest',
             'bioc_2.10.manifest',
             'bioc_2.11.manifest',
             'bioc_2.12.manifest',
             'bioc_2.13.manifest',
             'bioc_2.14.manifest',
             'bioc_2.2.manifest',
             'bioc_2.3.manifest',
             'bioc_2.4.manifest',
             'bioc_2.5.manifest',
             'bioc_2.6.manifest',
             'bioc_2.7.manifest',
             'bioc_2.8.manifest',
             'bioc_2.9.manifest',
             'bioc_3.0.manifest',
             'bioc_3.1.manifest',
             'bioc_3.2.manifest',
             'bioc_3.3.manifest',
             'bioc_3.4.manifest',
             'bioc_3.5.manifest',
             'find-package-files',
             'grep-package-files',
             'optOut.info',
             'repthemes.xml',
             'rpacks.test']
    return avoid
